import Head from 'next/head'
import Image from 'next/image'
import Vertical from '../components/Vertical'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Vertical/>    
    </div>
  )
}
